import getParamsFromRoute from '@libs/Navigation/helpers/getParamsFromRoute';
import {SPLIT_TO_SIDEBAR} from '@libs/Navigation/linkingConfig/RELATIONS';

import type {NavigationPartialRoute, State} from '@navigation/types';

import CONST from '@src/CONST';

import type {NavigationAction, NavigationState} from '@react-navigation/native';
import type {Writable} from 'type-fest';

import type {ActionPayload} from './types';

type MinimalAction = {
    action: Writable<NavigationAction>;
    targetState: State | undefined;
};

function hasDifferentSplitScope(currentRoute: NavigationPartialRoute, payload: ActionPayload): boolean {
    const sidebarScreen = SPLIT_TO_SIDEBAR[currentRoute.name as keyof typeof SPLIT_TO_SIDEBAR];
    if (!sidebarScreen || !currentRoute.state) {
        return false;
    }

    const scopeParams = getParamsFromRoute(sidebarScreen);
    const sidebarRoute = currentRoute.state.routes.find((route) => route.name === sidebarScreen);
    const targetParams = payload.params?.params;
    if (!sidebarRoute?.params || !targetParams || typeof targetParams !== 'object') {
        return false;
    }

    return scopeParams.some((param) => {
        const currentValue = (sidebarRoute.params as Record<string, unknown>)[param];
        const targetValue = (targetParams as Record<string, unknown>)[param];
        return currentValue !== undefined && targetValue !== undefined && currentValue !== targetValue;
    });
}

/**
 * Motivation for this function is described in NAVIGATION.md
 *
 * @param action action generated by getActionFromState
 * @param state The root state
 * @returns minimalAction minimal action is the action that we should dispatch
 */
function getMinimalAction(action: NavigationAction, state: NavigationState): MinimalAction {
    let currentAction: NavigationAction = action;
    let currentState: State | undefined = state;
    let currentTargetKey: string | undefined;

    while (currentAction.payload && 'name' in currentAction.payload && currentState?.routes[currentState.index ?? -1].name === currentAction.payload.name) {
        const currentRoute = currentState.routes[currentState.index ?? -1];
        const payload = currentAction.payload as ActionPayload;
        const isDifferentSplitScope = hasDifferentSplitScope(currentRoute, payload);
        if (!currentRoute.state || isDifferentSplitScope) {
            if (isDifferentSplitScope) {
                currentAction = {...currentAction, type: CONST.NAVIGATION.ACTION_TYPE.PUSH};
            }
            break;
        }

        currentState = currentRoute.state;
        currentTargetKey = currentState?.key;

        // Creating new smaller action
        currentAction = {
            type: currentAction.type,
            payload: {
                name: payload?.params?.screen,
                params: payload?.params?.params,
                path: payload?.params?.path,
            },
            target: currentTargetKey,
        };
    }
    return {action: currentAction, targetState: currentState};
}

export default getMinimalAction;
